## Numpy

In [14]:
# Пример расчета функции на сетке без использования Numpy
from array import array
import math

def func(x):
    return math.sin(x) * math.cos(3 * x)

minval = 0
maxval = 10
count = 101
step = (maxval - minval) / (count - 1)

xdata = array('d', [0] * count)
ydata = array('d', [0] * count)

for n in range(count):
    xdata[n] = minval + n * step
    ydata[n] = func(xdata[n])

print(f"{xdata=}")
print(f"{ydata=}")

xdata=array('d', [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2000000000000002, 1.3, 1.4000000000000001, 1.5, 1.6, 1.7000000000000002, 1.8, 1.9000000000000001, 2.0, 2.1, 2.2, 2.3000000000000003, 2.4000000000000004, 2.5, 2.6, 2.7, 2.8000000000000003, 2.9000000000000004, 3.0, 3.1, 3.2, 3.3000000000000003, 3.4000000000000004, 3.5, 3.6, 3.7, 3.8000000000000003, 3.9000000000000004, 4.0, 4.1000000000000005, 4.2, 4.3, 4.4, 4.5, 4.6000000000000005, 4.7, 4.800000000000001, 4.9, 5.0, 5.1000000000000005, 5.2, 5.300000000000001, 5.4, 5.5, 5.6000000000000005, 5.7, 5.800000000000001, 5.9, 6.0, 6.1000000000000005, 6.2, 6.300000000000001, 6.4, 6.5, 6.6000000000000005, 6.7, 6.800000000000001, 6.9, 7.0, 7.1000000000000005, 7.2, 7.300000000000001, 7.4, 7.5, 7.6000000000000005, 7.7, 7.800000000000001, 7.9, 8.0, 8.1, 8.200000000000001, 8.3, 8.4, 8.5, 8.6, 8.700000000000001, 8.8, 8.9, 9.0, 9.1, 9.200000000000001, 9.3, 9.4, 9.5, 9.60000000000000

In [15]:
# Пример расчета функции на сетке с использованием Numpy
import numpy as np

def func(x):
    return np.sin(x) * np.cos(3 * x)

minval = 0
maxval = 10
count = 101

xdata = np.linspace(minval, maxval, count)
ydata = func(xdata)

print(f"{type(xdata)=}")
print(f"{xdata=}")
print(f"{type(ydata)=}")
print(f"{ydata=}")

type(xdata)=<class 'numpy.ndarray'>
xdata=array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])
type(ydata)=<class 'numpy.ndarray'>
ydata=array([ 0.        ,  0.09537451,  0.16396887,  0.18369831,  0.14110876,
        0.03391322, -0.12828795, -0.32523079, -0.52897387, -0.70818404,
       -0.83304996, -0.88004924, -0.83581389, -0.69947801, -0.48312739,
       -0.21026775,  0.

In [16]:
# Создание массивов, заполненных нулями
import numpy as np

foo = np.zeros(5)
foo_2d = np.zeros((3, 4))
foo_3d = np.zeros((3, 4, 5))

print(f"{type(foo)=}")
print(f"{foo}")
print()
print(f"{type(foo_2d)=}")
print(f"{foo_2d}")
print()
print(f"{type(foo_3d)=}")
print(f"{foo_3d}")

type(foo)=<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]

type(foo_2d)=<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

type(foo_3d)=<class 'numpy.ndarray'>
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [17]:
# Создание массивов, заполненных единицами
import numpy as np

foo = np.ones(5)
foo_2d = np.ones((3, 4))

print("foo:")
print(f"{foo}")
print()
print("foo_2d:")
print(f"{foo_2d}")

foo:
[1. 1. 1. 1. 1.]

foo_2d:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
# Создание массива, заполненного заданным значением
import numpy as np

value = 10

foo = np.full(5, value)
bar = np.full((3, 5), value)

print("foo:")
print(foo)
print()
print("bar:")
print(bar)

foo:
[10 10 10 10 10]

bar:
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [19]:
# Создание единичной матрицы
import numpy as np

foo = np.eye(3)
bar = np.eye(5, k=2)
baz = np.eye(5, k=-2)

print("foo:")
print(foo)
print()
print("bar:")
print(bar)
print()
print("baz:")
print(baz)

foo:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

bar:
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

baz:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [20]:
# Создание массивов, заполненных последовательностью чисел
import numpy as np

foo = np.arange(1.0, 2.0, 0.1)
bar = np.arange(1.0, 10.0)
baz = np.arange(10.0)
spam = np.linspace(1.0, 2.0, 11)

print(f"{foo=}")
print()
print(f"{bar=}")
print()
print(f"{baz=}")
print()
print(f"{spam=}")

foo=array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

bar=array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

baz=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

spam=array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])


In [21]:
# Создание массивов, заполненных псевдослучайными числами
import numpy as np
from numpy.random import rand

foo = rand(3, 4)
bar = rand(3, 4) * 2 - 1
baz = np.round(rand(3, 4) * 10)

print("foo:")
print(f"{foo}")
print()
print("bar:")
print(f"{bar}")
print()
print("baz:")
print(f"{baz}")

foo:
[[0.74254403 0.58444078 0.08605242 0.23951751]
 [0.86553827 0.73993122 0.21620309 0.32934796]
 [0.55374691 0.68069331 0.14404983 0.53221344]]

bar:
[[-0.3511179   0.83782896  0.48190342  0.04809147]
 [-0.50465597 -0.30269233 -0.54914455 -0.04871352]
 [ 0.50251321  0.74824977 -0.17864563 -0.19694475]]

baz:
[[ 2.  8. 10.  0.]
 [ 4.  6.  9.  8.]
 [ 8.  6.  7.  5.]]


In [22]:
# Методы и свойства массивов ndarray
import numpy as np

foo = np.zeros((3, 4))
print(dir(foo))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [23]:
# Свойство shape и транспонирование матрицы
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.shape=}")
print()
print(f"{foo.T}")
print()
print(f"{foo.T.shape=}")


[[ 7.  1.  1. 10.]
 [ 8.  5.  2.  7.]
 [ 2.  4. 10.  3.]]

foo.shape=(3, 4)

[[ 7.  8.  2.]
 [ 1.  5.  4.]
 [ 1.  2. 10.]
 [10.  7.  3.]]

foo.T.shape=(4, 3)


In [24]:
# Расчет суммы и произведения элементов массива
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.sum()=}")
print(f"{foo.sum(axis=0)=}")
print(f"{foo.sum(axis=1)=}")
print()
print(f"{foo.prod()=}")
print(f"{foo.prod(axis=0)=}")
print(f"{foo.prod(axis=1)=}")

[[ 0.  4.  8.  8.]
 [ 3.  1.  4.  9.]
 [ 4. 10.  3.  2.]]

foo.sum()=56.0
foo.sum(axis=0)=array([ 7., 15., 15., 19.])
foo.sum(axis=1)=array([20., 17., 19.])

foo.prod()=0.0
foo.prod(axis=0)=array([  0.,  40.,  96., 144.])
foo.prod(axis=1)=array([  0., 108., 240.])


In [25]:
# Нахождение минимального, максимального и среднего значений
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.min()=}")
print(f"{foo.min(axis=0)=}")
print(f"{foo.min(axis=1)=}")
print()
print(f"{foo.max()=}")
print(f"{foo.max(axis=0)=}")
print(f"{foo.max(axis=1)=}")
print()
print(f"{foo.mean()=}")
print(f"{foo.mean(axis=0)=}")
print(f"{foo.mean(axis=1)=}")

[[ 4.  5.  1.  3.]
 [ 2.  7. 10.  6.]
 [ 6.  2.  2.  3.]]

foo.min()=1.0
foo.min(axis=0)=array([2., 2., 1., 3.])
foo.min(axis=1)=array([1., 2., 2.])

foo.max()=10.0
foo.max(axis=0)=array([ 6.,  7., 10.,  6.])
foo.max(axis=1)=array([ 5., 10.,  6.])

foo.mean()=4.25
foo.mean(axis=0)=array([4.        , 4.66666667, 4.33333333, 4.        ])
foo.mean(axis=1)=array([3.25, 6.25, 3.25])


In [26]:
# Нахождение индексов минимального и максимального значений
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.argmin()=}")
print(f"{foo.argmin(axis=0)=}")
print(f"{foo.argmin(axis=1)=}")
print()
print(f"{foo.argmax()=}")
print(f"{foo.argmax(axis=0)=}")
print(f"{foo.argmax(axis=1)=}")

[[ 3.  9. 10.  4.]
 [ 7.  9.  2.  1.]
 [ 4.  6.  4.  7.]]

foo.argmin()=7
foo.argmin(axis=0)=array([0, 2, 1, 1])
foo.argmin(axis=1)=array([0, 3, 0])

foo.argmax()=2
foo.argmax(axis=0)=array([1, 0, 0, 2])
foo.argmax(axis=1)=array([2, 1, 3])


In [27]:
# Изменение формы массива
import numpy as np
from numpy.random import rand

foo = np.round(rand(12) * 10)

print("foo:")
print(f"{foo}")
print()

bar = foo.reshape((3, 4))
baz = foo.reshape((2, 6))

print("bar:")
print(f"{bar}")
print()
print("baz:")
print(f"{baz}")

foo:
[ 7.  0.  5.  9.  3.  1.  8. 10.  7.  3.  3. 10.]

bar:
[[ 7.  0.  5.  9.]
 [ 3.  1.  8. 10.]
 [ 7.  3.  3. 10.]]

baz:
[[ 7.  0.  5.  9.  3.  1.]
 [ 8. 10.  7.  3.  3. 10.]]


In [28]:
# Ошибка при изменении формы массива
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()

# Ошибка!
# bar = foo.reshape((3, 7))

[[ 2.  7.  1.  4.]
 [ 6. 10.  5.  4.]
 [ 5.  1. 10.  4.]]



In [29]:
# Изменение размера массива
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()

foo.resize((3, 5))
print(f"{foo}")
print()

foo.resize((3, 2))
print(f"{foo}")

[[5. 1. 8. 5.]
 [3. 7. 0. 5.]
 [8. 6. 3. 6.]]

[[5. 1. 8. 5. 3.]
 [7. 0. 5. 8. 6.]
 [3. 6. 0. 0. 0.]]

[[5. 1.]
 [8. 5.]
 [3. 7.]]


In [30]:
# Выделение срезов для одномерных массивов
import numpy as np

# Создаем массив и выделяем его срез
foo_ndarray = np.arange(0, 10)
slice_ndarray = foo_ndarray[3: 7]

# Создаем список и выделяем его срез
foo_list = list(range(0, 10))
slice_list = foo_list[3: 7]

print("Первоначальное состояние")
print(f"{foo_ndarray=}")
print(f"{slice_ndarray=}")
print(f"{foo_list=}")
print(f"{slice_list=}")
print()

# Изменяем элементы в срезе массива и списка
slice_ndarray[:] = 100
slice_list[:] = [100] * len(slice_list)

print("После изменения элементов среза")
print(f"{foo_ndarray=}")
print(f"{slice_ndarray=}")
print(f"{foo_list=}")
print(f"{slice_list=}")

Первоначальное состояние
foo_ndarray=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_ndarray=array([3, 4, 5, 6])
foo_list=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
slice_list=[3, 4, 5, 6]

После изменения элементов среза
foo_ndarray=array([  0,   1,   2, 100, 100, 100, 100,   7,   8,   9])
slice_ndarray=array([100, 100, 100, 100])
foo_list=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
slice_list=[100, 100, 100, 100]


In [31]:
# Выделение срезов для одномерных массивов
import numpy as np

foo_ndarray = np.arange(0, 10)
slice_ndarray = foo_ndarray[2: 7: 2]

print(f"{foo_ndarray=}")
print(f"{slice_ndarray=}")

foo_ndarray=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_ndarray=array([2, 4, 6])


In [32]:
# Выделение срезов для одномерных массивов
import numpy as np

foo_ndarray = np.arange(0, 10)
slice_ndarray = foo_ndarray[3:]

print(f"{foo_ndarray=}")
print(f"{slice_ndarray=}")

foo_ndarray=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_ndarray=array([3, 4, 5, 6, 7, 8, 9])


In [33]:
# Выделение срезов для одномерных массивов
import numpy as np

foo_ndarray = np.arange(0, 10)
slice_ndarray = foo_ndarray[:5]

print(f"{foo_ndarray=}")
print(f"{slice_ndarray=}")

foo_ndarray=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_ndarray=array([0, 1, 2, 3, 4])


In [34]:
# Создание копии массивов
import numpy as np

foo = np.arange(0, 10)
foo_slice = foo[:]
foo_copy = foo.copy()

print("Первоначальное состояние")
print(f"{foo=}")
print(f"{foo_slice=}")
print(f"{foo_copy=}")
print()

foo_copy[5:] = 0

print("После изменения элементов копии")
print(f"{foo=}")
print(f"{foo_copy=}")
print()

foo_slice[5:] = 0

print("После изменения элементов среза")
print(f"{foo=}")
print(f"{foo_slice=}")

Первоначальное состояние
foo=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_slice=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_copy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

После изменения элементов копии
foo=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_copy=array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

После изменения элементов среза
foo=array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])
foo_slice=array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])


In [35]:
# Создание копии массивов
import numpy as np

foo = np.arange(0, 10)
foo_slice = np.array(foo, copy=False)

# copy=True - это значение по умолчанию
foo_copy = np.array(foo, copy=True)

# Аналогично строке:
# foo_copy = np.array(foo)

print("Первоначальное состояние")
print(f"{foo=}")
print(f"{foo_slice=}")
print(f"{foo_copy=}")
print()

foo_copy[5:] = 0

print("После изменения элементов копии")
print(f"{foo=}")
print(f"{foo_copy=}")
print()

foo_slice[5:] = 0

print("После изменения элементов среза")
print(f"{foo=}")
print(f"{foo_slice=}")

Первоначальное состояние
foo=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_slice=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_copy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

После изменения элементов копии
foo=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_copy=array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

После изменения элементов среза
foo=array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])
foo_slice=array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])


In [36]:
# Создание копии среза
import numpy as np

foo = np.arange(0, 10)
foo_slice_copy = foo[3: 7].copy()

print("Первоначальное состояние")
print(f"{foo=}")
print(f"{foo_slice_copy=}")
print()

foo_slice_copy[:] = 0

print("После изменения элементов копии среза")
print(f"{foo=}")
print(f"{foo_slice_copy=}")

Первоначальное состояние
foo=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_slice_copy=array([3, 4, 5, 6])

После изменения элементов копии среза
foo=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
foo_slice_copy=array([0, 0, 0, 0])


In [37]:
# Выделение срезов для двумерных массивов
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 25).reshape((5, 5))
print("matrix:")
print(matrix)
print()

bar = matrix[1:4, 1:3]

print("bar:")
print(bar)

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

bar:
[[ 6  7]
 [11 12]
 [16 17]]


In [38]:
# Выделение строк двумерных массивов
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 25).reshape((5, 5))
print("matrix:")
print(matrix)
print()

bar = matrix[1:4, :]

print("bar:")
print(bar)

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

bar:
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
# Выделение строки двумерного массива
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 25).reshape((5, 5))
print("matrix:")
print(matrix)
print()

bar = matrix[2, :]

print("bar:")
print(bar)

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

bar:
[10 11 12 13 14]


In [40]:
# Выделение столбцов двумерных массивов
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 25).reshape((5, 5))
print("matrix:")
print(matrix)
print()

bar = matrix[:, 1:3]

print("bar:")
print(bar)

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

bar:
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [41]:
# Выделение столбца двумерного массива
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 25).reshape((5, 5))
print("matrix:")
print(matrix)
print()

bar = matrix[:, 2]

print("bar:")
print(bar)

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

bar:
[ 2  7 12 17 22]


In [42]:
# Выделение срезов для двумерных массивов
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 36).reshape((6, 6))
print("matrix:")
print(matrix)
print()

bar = matrix[1:7:2, 1:7:2]

print("bar:")
print(bar)

matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

bar:
[[ 7  9 11]
 [19 21 23]
 [31 33 35]]


In [43]:
# Модификация срезов двумерных массивов
import numpy as np

# Создание матрицы из последовательности целых чисел
matrix = np.arange(0, 36).reshape((6, 6))
bar = matrix[1:7:2, 1:7:2]

print("До изменения среза")
print("matrix:")
print(matrix)
print()

print("bar:")
print(bar)
print()

bar[:,:] = 0

print("После изменения среза")
print("matrix:")
print(matrix)
print()

print("bar:")
print(bar)
print()

До изменения среза
matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

bar:
[[ 7  9 11]
 [19 21 23]
 [31 33 35]]

После изменения среза
matrix:
[[ 0  1  2  3  4  5]
 [ 6  0  8  0 10  0]
 [12 13 14 15 16 17]
 [18  0 20  0 22  0]
 [24 25 26 27 28 29]
 [30  0 32  0 34  0]]

bar:
[[0 0 0]
 [0 0 0]
 [0 0 0]]



In [44]:
# Булевы массивы
import numpy as np

matrix = np.arange(0, 25).reshape((5, 5))
matrix_bool_1 = matrix > 10
matrix_bool_2 = matrix % 2 == 0

print("matrix:")
print(matrix)
print()

print("matrix_bool_1:")
print(matrix_bool_1)
print()

print("matrix_bool_2:")
print(matrix_bool_2)
print()

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

matrix_bool_1:
[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

matrix_bool_2:
[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]



In [45]:
# Булевы массивы
import numpy as np

matrix = np.arange(0, 25).reshape((5, 5))
matrix_bool = matrix > 10

bar = matrix[matrix_bool]

print("matrix:")
print(matrix)
print()

print("matrix_bool:")
print(matrix_bool)
print()

print("bar:")
print(bar)
print()

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

matrix_bool:
[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]

bar:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [46]:
# Булевы массивы
import numpy as np

matrix = np.arange(0, 25).reshape((5, 5))
matrix_bool = matrix > 10
matrix[matrix_bool] = 10

print("matrix:")
print(matrix)
print()

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]



In [47]:
# Булевы массивы
import numpy as np

matrix = np.arange(0, 25).reshape((5, 5))
matrix[matrix > 10] = 10

print("matrix:")
print(matrix)
print()

matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]



In [48]:
# Булевы массивы
import numpy as np

matrix = np.arange(0, 25).reshape((5, 5))
matrix[matrix % 2 == 0] = 0

print("matrix:")
print(matrix)
print()

matrix:
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]



In [61]:
# Булевы массивы
import numpy as np

foo = np.array([[True, True, True], 
                [True, False, True], 
                [False, False, False]])
print("foo:")
print(foo)
print()

print(f"{foo.all()=}")
print(f"{foo.all(axis=0)=}")
print(f"{foo.all(axis=1)=}")
print(f"{foo.any()=}")
print(f"{foo.any(axis=0)=}")
print(f"{foo.any(axis=1)=}")

foo:
[[ True  True  True]
 [ True False  True]
 [False False False]]

foo.all()=False
foo.all(axis=0)=array([False, False, False])
foo.all(axis=1)=array([ True, False, False])
foo.any()=True
foo.any(axis=0)=array([ True,  True,  True])
foo.any(axis=1)=array([ True,  True, False])


In [91]:
# Булевы массивы
import numpy as np
from numpy.random import rand

foo = np.round(rand(3, 3) * 10)

print("foo:")
print(f"{foo}")
print()
print(f"{(foo < 10).all()=}")
print(f"{(foo >= 10).any()=}")

foo:
[[4. 5. 7.]
 [2. 4. 8.]
 [3. 3. 7.]]

(foo < 10).all()=True
(foo >= 10).any()=False
