## Numpy

In [26]:
# Пример расчета функции на сетке без использования Numpy
from array import array
import math

def func(x):
    return math.sin(x) * math.cos(3 * x)

minval = 0
maxval = 10
count = 101
step = (maxval - minval) / (count - 1)

xdata = array('d', [0] * count)
ydata = array('d', [0] * count)

for n in range(count):
    xdata[n] = minval + n * step
    ydata[n] = func(xdata[n])

print(f"{xdata=}")
print(f"{ydata=}")

xdata=array('d', [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0, 1.1, 1.2000000000000002, 1.3, 1.4000000000000001, 1.5, 1.6, 1.7000000000000002, 1.8, 1.9000000000000001, 2.0, 2.1, 2.2, 2.3000000000000003, 2.4000000000000004, 2.5, 2.6, 2.7, 2.8000000000000003, 2.9000000000000004, 3.0, 3.1, 3.2, 3.3000000000000003, 3.4000000000000004, 3.5, 3.6, 3.7, 3.8000000000000003, 3.9000000000000004, 4.0, 4.1000000000000005, 4.2, 4.3, 4.4, 4.5, 4.6000000000000005, 4.7, 4.800000000000001, 4.9, 5.0, 5.1000000000000005, 5.2, 5.300000000000001, 5.4, 5.5, 5.6000000000000005, 5.7, 5.800000000000001, 5.9, 6.0, 6.1000000000000005, 6.2, 6.300000000000001, 6.4, 6.5, 6.6000000000000005, 6.7, 6.800000000000001, 6.9, 7.0, 7.1000000000000005, 7.2, 7.300000000000001, 7.4, 7.5, 7.6000000000000005, 7.7, 7.800000000000001, 7.9, 8.0, 8.1, 8.200000000000001, 8.3, 8.4, 8.5, 8.6, 8.700000000000001, 8.8, 8.9, 9.0, 9.1, 9.200000000000001, 9.3, 9.4, 9.5, 9.60000000000000

In [28]:
# Пример расчета функции на сетке с использованием Numpy
import numpy as np

def func(x):
    return np.sin(x) * np.cos(3 * x)

minval = 0
maxval = 10
count = 101

xdata = np.linspace(minval, maxval, count)
ydata = func(xdata)

print(f"{type(xdata)=}")
print(f"{xdata=}")
print(f"{type(ydata)=}")
print(f"{ydata=}")

type(xdata)=<class 'numpy.ndarray'>
xdata=array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])
type(ydata)=<class 'numpy.ndarray'>
ydata=array([ 0.        ,  0.09537451,  0.16396887,  0.18369831,  0.14110876,
        0.03391322, -0.12828795, -0.32523079, -0.52897387, -0.70818404,
       -0.83304996, -0.88004924, -0.83581389, -0.69947801, -0.48312739,
       -0.21026775,  0.

In [38]:
# Создание массивов Numpy, заполненных нулями
import numpy as np

foo = np.zeros(5)
foo_2d = np.zeros((3, 4))
foo_3d = np.zeros((3, 4, 5))

print(f"{type(foo)=}")
print(f"{foo}")
print()
print(f"{type(foo_2d)=}")
print(f"{foo_2d}")
print()
print(f"{type(foo_3d)=}")
print(f"{foo_3d}")

type(foo)=<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]

type(foo_2d)=<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

type(foo_3d)=<class 'numpy.ndarray'>
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [33]:
# Создание массивов Numpy, заполненных единицами
import numpy as np

foo = np.ones(5)
foo_2d = np.ones((3, 4))

print(f"{foo}")
print()
print(f"{foo_2d}")

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
# Создание единичной матрицы
import numpy as np

foo = np.eye(3)
bar = np.eye(5, k=2)

print(foo)
print()
print(bar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
# Создание массива, заполненного заданным значением
import numpy as np

value = 10

foo = np.full(5, value)
bar = np.full((3, 5), value)

print(foo)
print()
print(bar)

[10 10 10 10 10]

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [50]:
# Создание массивов, заполненных последовательностью чисел
import numpy as np

foo = np.arange(1.0, 2.0, 0.1)
bar = np.arange(1.0, 10.0)
baz = np.arange(10.0)
spam = np.linspace(1.0, 2.0, 11)

print(f"{foo=}")
print()
print(f"{bar=}")
print()
print(f"{baz=}")
print()
print(f"{spam=}")

foo=array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

bar=array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

baz=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

spam=array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])


In [53]:
# Создание массивов, заполненных случайными числами
from numpy.random import rand

foo = rand(3, 4)
bar = rand(3, 4) * 2 - 1

print(f"{foo}")
print()
print(f"{bar}")

[[0.41051537 0.6603087  0.78040919 0.3147437 ]
 [0.15215242 0.01831297 0.34964879 0.78321118]
 [0.72880162 0.11398753 0.54571451 0.6963709 ]]

[[-0.50537632  0.45000892 -0.76949472  0.3133065 ]
 [-0.7653202   0.28688652 -0.81511716  0.09936856]
 [-0.43253089 -0.71472923  0.95610258  0.68262218]]


In [63]:
# Методы и свойства массивов ndarray
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)
print(dir(foo))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', 

In [78]:
# Методы и свойства массивов ndarray
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.T}")
print()
print(f"{foo.shape=}")


[[ 3.  1.  9.  5.]
 [ 4.  3.  6.  5.]
 [10.  0.  9.  4.]]

[[ 3.  4. 10.]
 [ 1.  3.  0.]
 [ 9.  6.  9.]
 [ 5.  5.  4.]]

foo.shape=(3, 4)


In [77]:
# Расчет суммы и произведения элементов
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.sum()=}")
print(f"{foo.sum(axis=0)=}")
print(f"{foo.sum(axis=1)=}")
print()
print(f"{foo.prod()=}")
print(f"{foo.prod(axis=0)=}")
print(f"{foo.prod(axis=1)=}")

[[ 9.  2. 10.  6.]
 [ 6.  8.  5.  9.]
 [ 6.  8.  6.  8.]]

foo.sum()=83.0
foo.sum(axis=0)=array([21., 18., 21., 23.])
foo.sum(axis=1)=array([27., 28., 28.])

foo.prod()=5374771200.0
foo.prod(axis=0)=array([324., 128., 300., 432.])
foo.prod(axis=1)=array([1080., 2160., 2304.])


In [81]:
# Нахождение минимального, максимального и среднего значений
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.min()=}")
print(f"{foo.min(axis=0)=}")
print(f"{foo.min(axis=1)=}")
print()
print(f"{foo.max()=}")
print(f"{foo.max(axis=0)=}")
print(f"{foo.max(axis=1)=}")
print()
print(f"{foo.mean()=}")
print(f"{foo.mean(axis=0)=}")
print(f"{foo.mean(axis=1)=}")

[[4. 4. 5. 3.]
 [8. 7. 8. 5.]
 [2. 8. 4. 6.]]

foo.min()=2.0
foo.min(axis=0)=array([2., 4., 4., 3.])
foo.min(axis=1)=array([3., 5., 2.])

foo.max()=8.0
foo.max(axis=0)=array([8., 8., 8., 6.])
foo.max(axis=1)=array([5., 8., 8.])

foo.mean()=5.333333333333333
foo.mean(axis=0)=array([4.66666667, 6.33333333, 5.66666667, 4.66666667])
foo.mean(axis=1)=array([4., 7., 5.])


In [83]:
# Нахождение индексов минимального и максимального значений
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()
print(f"{foo.argmin()=}")
print(f"{foo.argmin(axis=0)=}")
print(f"{foo.argmin(axis=1)=}")
print()
print(f"{foo.argmax()=}")
print(f"{foo.argmax(axis=0)=}")
print(f"{foo.argmax(axis=1)=}")

[[ 4.  7.  1.  9.]
 [ 6.  8.  9.  4.]
 [ 9.  4. 10.  9.]]

foo.argmin()=2
foo.argmin(axis=0)=array([0, 2, 0, 1], dtype=int64)
foo.argmin(axis=1)=array([2, 3, 1], dtype=int64)

foo.argmax()=10
foo.argmax(axis=0)=array([2, 1, 2, 0], dtype=int64)
foo.argmax(axis=1)=array([3, 2, 2], dtype=int64)


In [84]:
# Изменение формы массива
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()

bar = foo.reshape((1, 12))
baz = foo.reshape((2, 6))

print(f"{bar}")
print()
print(f"{baz}")

[[ 3. 10.  7.  3.]
 [ 1.  5.  2.  2.]
 [ 1.  8.  6.  9.]]

[[ 3. 10.  7.  3.  1.  5.  2.  2.  1.  8.  6.  9.]]

[[ 3. 10.  7.  3.  1.  5.]
 [ 2.  2.  1.  8.  6.  9.]]


In [86]:
# Ошибка при изменении формы массива
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()

# Ошибка!
# bar = foo.reshape((3, 5))

[[ 0.  1.  2. 10.]
 [ 6.  0.  3.  9.]
 [ 3.  7.  4.  9.]]



In [90]:
# Изменение размера массива
from numpy.random import rand

foo = np.round(rand(3, 4) * 10)

print(f"{foo}")
print()

foo.resize((3, 5))
print(f"{foo}")
print()

foo.resize((3, 2))
print(f"{foo}")

[[ 1.  2.  6.  2.]
 [ 1.  2.  4. 10.]
 [ 0.  4.  1.  3.]]

[[ 1.  2.  6.  2.  1.]
 [ 2.  4. 10.  0.  4.]
 [ 1.  3.  0.  0.  0.]]

[[1. 2.]
 [6. 2.]
 [1. 2.]]


In [91]:
# Выделение срезов для одномерных массивов

In [92]:
# Выделение срезов для двумерных массивов

In [ ]:
# Копирование массивов